services:
  hadoop:
    build: .
    container_name: hadoop-single-node
    hostname: hadoop
    user: root

    ports:
      - "9870:9870"
      - "8088:8088"
      - "9864:9864"
      - "9002:9000"
      - "19888:19888"
      - "8042:8042"

    environment:
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_USER_NAME=alex
      - HDFS_NAMENODE_USER=alex
      - HDFS_DATANODE_USER=alex
      - HDFS_SECONDARYNAMENODE_USER=alex
      - YARN_RESOURCEMANAGER_USER=alex
      - YARN_NODEMANAGER_USER=alex
      - CORE-SITE.XML_fs.defaultFS=hdfs://hadoop:8020
      - HDFS-SITE.XML_dfs.namenode.rpc-address=hadoop:8020
      - HDFS-SITE.XML_dfs.replication=1
      - HDFS-SITE.XML_dfs.namenode.name.dir=/opt/hadoop/data/namenode
      - HDFS-SITE.XML_dfs.datanode.data.dir=/opt/hadoop/data/datanode
      - MAPRED-SITE.XML_mapreduce.framework.name=yarn
      - YARN-SITE.XML_yarn.resourcemanager.hostname=hadoop
      - YARN-SITE.XML_yarn.nodemanager.aux-services=mapreduce_shuffle
      - YARN-SITE.XML_yarn.nodemanager.pmem-check-enabled=false
      - YARN-SITE.XML_yarn.nodemanager.vmem-check-enabled=false
      - HDFS-SITE.XML_dfs.webhdfs.enabled=true
      - HDFS-SITE.XML_dfs.namenode.http-address=0.0.0.0:9870

    volumes:
      - ./hadoop_data:/opt/hadoop/data
      - ./hadoop_data/logs:/opt/hadoop/logs

volumes:
  hadoop_data: